name: Deploy API to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 039612861404.dkr.ecr.us-east-2.amazonaws.com
          IMAGE_NAME: mi-api
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest

      - name: Register new ECS task definition
        run: |
          aws ecs register-task-definition --cli-input-json file://task-definition.json

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster mi-cluster --service mi-api-servicio --force-new-deployment
